#!/bin/bash

set -e

cd adpcm/src/
make clean
cd ../..

cd bitcount/
make clean
cd ..

cd basicmath/
make clean
cd ..

cd blowfish/
make clean
cd ..

cd CRC32/
make clean
cd ..

cd dijkstra/
make clean
cd ..

cd FFT/
make clean
cd ..

cd gsm/
make clean
cd ..

cd jpeg/jpeg-6a/
make clean
cd ../..

cd lame/lame3.70/
make clean
cd ../..

cd patricia/
make clean
cd ..

cd qsort/
make clean
cd ..

cd sha/
make clean
cd ..

cd susan/
make clean
cd ..

cd typeset/lout-3.24
make clean
cd ../..

